#!/usr/bin/env bash
# A lil' bit configuration of the subdomains

domain_config () {
    payload=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $payload" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domain_config "$1" "www"
  domain_config "$1" "lb-01"
  domain_config "$1" "web-01"
  domain_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_config "$1" "$2"
fi
