#!/usr/bin/env bash
# Install Nginx

apt-get update
apt-get install -y nginx

# Create a temporary HTML file with "Hello World!" string as content
echo "<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>" > /var/www/html/index.html

# Configure the nginx server to listen on port 80
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart nginx without systemctl
service nginx restart
