#!/usr/bin/env bash
# Configure a new Ubuntu machine to redirect

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sub="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.goofle.com permanent;"
sudo sed -i "s/server_name _;/$sub/" /etc/nginx/sites-enabled/default

sudo service nginx restart
