#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Creating a custom 404 error page with the string: Ceci n'est pas une page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configuring Nginx to use the custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sub="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$sub/" /etc/nginx/sites-enabled/default

# Lastly, restart Nginx
service nginx restart

