#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

# Creating a custom 404 error page with the string: Ceci n'est pas une page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configuring Nginx to use the custom 404 error page
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

# Lastly, restart Nginx
service nginx restart

