#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get install -y nginx

err="/usr/share/nginx/html/404error.html"
content="Ceci n'est pas une page"
err_redirect="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html>"
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://https://github.com/kc-clintone;\n\t}\n"
file="/etc/nginx/sites-available/default"

ufw allow 'Nginx HTTP'
sudo echo "$Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $redirect" "$file"

echo "$content" > "$err"
sed -i "37i\ $err_redirect" "$file"

# Lastly, restart nginx
service nginx restart
