#!/usr/bin/env bash

# Update the package repository
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Create a custom Nginx configuration file to add the custom header
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_header.conf

# Remove default configuration files if they exist
sudo rm /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default

# Configure Nginx settings
sudo bash -c 'cat > /etc/nginx/sites-available/default' <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Enable the custom configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Ensure Nginx is running
sudo systemctl restart nginx

