#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# load balancer's configuration
DN='xtremeart.tech'
INIT='/etc/default/haproxy'
CONFIG='/etc/haproxy/haproxy.cfg'
LB_CONFIG=\
"
#--$DOMAIN_NAME-params-begin--
backend $DN-backend
        balance roundrobin
        server 478643-web-01 34.224.2.251:80 check
        server 478643-web-02 52.91.121.119:80 check
frontend $DN-frontend
        bind *:80
        mode http
        default_backend $DN-backend
#--$DOMAIN_NAME-params-end--
"

[ -f "$INIT" ] || touch "$INIT"
[ -f "$CONFIG" ] || touch "$CONFIG"

CFG=$(grep -Eco "$N-backend" < $CONFIG)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT)" -gt 0 ]; then
        sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT"
else
        echo 'ENABLED=1' >> $INIT
fi

if [ "$CFG" -eq 0 ]; then
        echo -e "$LB_CONFIG" >> $CONFIG
else
        start_token="#--$DN-params-begin--"
        end_token="#--$DN-params-end--"
        a=$(grep -onE "$start_token" < "$CONFIG" | cut -d : -f1)
        b=$(grep -onE "$end_token" < "$CONFIG" | cut -d : -f1)
        a=$((a - 1))
        b=$((b + 1))
        sed -i "$a,$b"d "$CONFIG"
        echo -en "$LB_CONFIG" >> $CONFIG
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        service haproxy start
else
        service haproxy restart
fi
