#!/usr/bin/env bash
# installing load balancer

# Update the package repository
sudo apt update

# Install HAProxy
sudo apt install -y haproxy

# Configure HAProxy
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg' <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend xtremeart_frontend
    bind *:80
    stats uri /haproxy?stats
    default_backend xtremeart_backend

backend xtremeart_backend
    balance roundrobin
    server 478643-web-01 34.224.2.251:80 check
    server 478643-web-02 52.91.121.119:80 check
EOF

# Enable HAProxy init script
sudo systemctl enable haproxy

# Restart HAProxy
sudo systemctl restart haproxy
