#!/usr/bin/env bash
#This is a tricky program, see it for yourself

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do
    echo 'To infinity and beyond'
    sleep 2
done
