#!/usr/bin/env bash
#A Bash script that displays the content of the file /etc/passwd.

while IFS=':' read -r username uid home; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
done < /etc/passwd
