#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS.

while IFS=':' read -r username x uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $x, more info about the user here: $info"
done < /etc/passwd
