#!/usr/bin/env bash
# While loop to display "Best School" with special condition for
# the 9th iteration that says Hi and continues

counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi
    ((counter++))
done
