#!/usr/bin/env bash
#A Bash script to display time for 12 hours and 59 minutes

hour=0
minute=1
while [ $hour -le 12 ]; do
    if [ $hour -eq 12 ]; then
        echo "Hour: 1"
    else
        echo "Hour: $hour"
    fi
    while [ $minute -le 59 ]; do
        echo $minute
        minute=$((minute + 1))
    done
    minute=0
    hour=$((hour + 1))
done
